version: 2.1

jobs:
  build:
    parameters:
      otp_version:
        type: string
        default: latest
    docker:
      - image: erlang:<< parameters.otp_version >>
    steps:
      - checkout
      - run:
          name: build
          command: make

workflows:
  all:
    jobs:
      - build:
          otp_version: "21"
      - build:
          otp_version: "20"
      - build:
          otp_version: "19"
      - build:
          otp_version: "18"
